version: '2.2'

#networks:
#  frontend:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.22.0.0/24

services:

  redis:
    image: redis
    container_name: edumeet_redis
    restart: unless-stopped
    ports:
    - 6379:6379
 #   networks:
 #   - frontend

  pikaworker:
    image: dennismaier/pikaworker:latest
    container_name: edumeet_pikaworker
    restart: unless-stopped
    mem_limit: 4096m
    mem_reservation: 4096m
    user: nobody
    ports:
    - 8093:8093
    environment:
      - result_url=http://edumeet:8010
  #  networks:
  #    - frontend
    depends_on:
    - edumeet
    - rabbitMQ

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: edumeet_rabbitmq
    restart: unless-stopped
    ports:
    - 15672:15672
    - 32690:32690
    - 5672:5672
    - 5671:5671
    - 25672:25672
    - 4369:4369    
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   # networks:
   #   - frontend

  edumeet:    
    build: .
    container_name: edumeet
    restart: unless-stopped
    user: "${CURRENT_USER}"
    volumes:
    #- ${PWD}/..:/edumeet
    #- ${PWD}/config/edumeet-server-config.js:/edumeet/server/config/config.js:ro
    - ${PWD}/compose/config/edumeet-server-config.yaml:/edumeet/server/dist/config/config.yaml:ro
    #- ${PWD}/config/edumeet-app-config.js:/edumeet/app/public/config/config.js:ro
    #- ${PWD}/../app/public/config/config.example.js:/edumeet/app/public/config/config.js:ro
    #network_mode: "host"
    #networks:
    #  - frontend
    ports:
    - 8443:8443
    - 8010:8010
    depends_on:
    - redis
    - rabbitMQ


  coturn:
    image: coturn/coturn
    container_name: edumeet_coturn
    restart: unless-stopped
    network_mode: host
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "80:80"
      - "80:80/udp"
## STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
      - "443:443"
      - "443:443/udp"
      - 49160-49200:49160-49200/udp
    #environment:
    #- DETECT_EXTERNAL_IP=yes
    command:
    - --network=host
    - --min-port=49160
    - --max-port=49200
    - --log-file=stdout
    #- --lt-cred-mech
    - --no-auth
    - --verbose
    - --fingerprint
    - -X 192.168.178.35 
    - --mobility
    #- --allow-loopback-peers
    #- --no-tlsv1
    #- --no-tlsv1_1
    #- --realm=edumeet
    #- --listening-ip=0.0.0.0
    - --user=test:test123
    - --cert=/tls/cert.pem
    - --pkey=/tls/pkey.pem
    volumes:
    - ${PWD}/server/certs/edumeet-demo-cert.pem:/tls/cert.pem:ro
    - ${PWD}/server/certs/edumeet-demo-key.pem:/tls/pkey.pem:ro
