version: '3'

networks:
  edumeet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
  default2:


services:
  edumeet:
    build:
      context: ./
      dockerfile: ./compose/edumeet/Dockerfile
    container_name: edumeet
    restart: unless-stopped
    user: "${CURRENT_USER}"
    #volumes:
    #- ${PWD}/..:/edumeet
    - ${PWD}/config/edumeet-server-config.js:/edumeet/server/config/config.js:ro
    #- ${PWD}/config/edumeet-server-config.yaml:/edumeet/server/config/config.yaml:ro
    #- ${PWD}/config/edumeet-app-config.js:/edumeet/app/public/config/config.js:ro
    #- ${PWD}/../app/public/config/config.example.js:/edumeet/app/public/config/config.js:ro
    network_mode: "host"
    extra_hosts:
      redis: 172.22.0.2
    depends_on:
    - redis

  redis:
    image: redis
    container_name: edumeet_redis
    restart: unless-stopped
    networks:
      edumeet:
        ipv4_address: 172.22.0.2
      default2:

  nginx:
    image: nginx
    container_name: edumeet_nginx
    restart: unless-stopped
    ports:
    - 8443:443
    volumes:
    - ./nginx/cert.pem:/etc/nginx/cert.pem
    - ./nginx/key.pem:/etc/nginx/key.pem
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      edumeet: 172.22.0.1
    networks:
      default2:
    depends_on:
    - edumeet

