apiVersion: apps/v1
kind: Deployment
metadata:
  name: edumeet
  labels:
    app: edumeet    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edumeet
  template:
    metadata:
      labels:
        app: edumeet
    spec:
      setHostnameAsFQDN: true
      hostname: server
      subdomain: edumeet
      containers:
        - name: edumeet
          image: gtura/scmeet:v1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8443
          - containerPort: 8010
          volumeMounts:
          - name: config
            mountPath: "/edumeet/server/dist/config"
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: edumeet-server-config.yaml
          items:
          - key: config.yaml
            path: config.yaml
    #      - key: config.js
    #        path: config.js
---
apiVersion: v1
kind: Service
metadata:
  name: edumeet-test
  labels:
    app: edumeet
spec:
  ports:  
  - port: 8443
    name: httpx
    targetPort: 8443
  - port: 8010
    name: httpy
    targetPort: 8010  
  selector:
    app: edumeet