apiVersion: apps/v1
kind: Deployment
metadata:
  name: pika
  labels:
    app: pika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pika
  template:
    metadata:
      labels:
        app: pika
    spec:
      setHostnameAsFQDN: true
      hostname: pika
      subdomain: edumeet
      containers:
      - name: pika
        image: dennismaier/pikaworker:latest
        ports:
        - containerPort: 8093
        env:
          - name: rest_url
            value: http://server.edumeet.default.svc.cluster.local:8010
---
apiVersion: v1
kind: Service
metadata:
  name: pika
  labels:
    app: pika
spec:
  ports:
  - port: 8093
    targetPort: 8093
  selector:
    app: pika