apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: edumeet
spec:
  containers:
  - name: edumeet
    image: gtura/scmeet:v1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8443
    - containerPort: 8010
---
apiVersion: v1
kind: Pod
metadata:
  name: pikaworker
spec:
  containers:
  - name: pikaworker
    image: dennismaier/pikaworker:latest
    ports:
    - containerPort: 8093
    env:
      - name: rest_url
        value: http://edumeet.svc.cluster.local:8010
---
apiVersion: v1
kind: Service
metadata:
  name: svc-edumeet
  labels:
    app: edumeet
spec:
  ports:
  - port: 8443
    name: edumeet
  clusterIP: None
  selector:
    app: edumeet
---
apiVersion: v1
kind: ConfigMap
metadata:  
  name: edumeet-server-config.yaml
data:
  config.yaml: "### MEINS\nlisteningPort: 8443\nlisteningHost: 0.0.0.0\n\nfileTracker:
      \"wss://tracker.openwebtorrent.com\"\n\ntls:\n  cert: ./certs/edumeet-demo-cert.pem\n
      \ key:  ./certs/edumeet-demo-key.pem\n\n# turnAPIURI: \"https://host.domain.tld/turn\"\n#
      turnAPIKey: \"Your API key\"\n\nbackupTurnServers:\n- urls:\n  - \"stun:127.0.0.1:3478\"\n
      \ username: \"test\"\n  credential: \"test123\"\n\nredisOptions:\n  host: \"192.168.178.20\"\n
      \ port: \"6379\"\n  password: \"_REDIS_PASSWORD_\"\n  #url: \"redis://127.0.0.1:30030/1\"\n\nprometheus:\n
      \ enabled: false\n  deidentify: true\n  numeric: true\n  listen: host.domain.tld\n\nmediasoup:\n
      \ webRtcTransport:\n    listenIps:\n    - ip: \"0.0.0.0\"\n  plainRtpTransport:\n
      \   listenIp:\n    - ip: \"0.0.0.0\"\n    rtcpMux: true\n    comedia: false\n\nrabbitmqOptions:\n
      \ url: \"amqp://guest:guest@127.0.0.1:32690\"\n\nbentoML:\n  enabled: false\n
      \ URI: \"http://127.0.0.1:3000/predict_async\"\n\npika:\n  enabled: true\n\ncelery:\n
      \ enabled: false\n  \nemotion:\n  targetFps: 10\n  minFps: 5"