apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  setHostnameAsFQDN: true
  hostname: redis
  subdomain: edumeet
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: edumeet
spec:
  setHostnameAsFQDN: true
  hostname: server
  subdomain: edumeet
  containers:
    - name: edumeet
      image: gtura/scmeet:v1.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8443
      - containerPort: 8010
      volumeMounts:
      - name: config
        mountPath: "/edumeet/server/dist/config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: edumeet-server-config.yaml
      items:
      - key: config.yaml
        path: config.yaml
#      - key: config.js
#        path: config.js

---
apiVersion: v1
kind: Pod
metadata:
  name: pikaworker
spec:
  setHostnameAsFQDN: true
  hostname: pikaworker
  subdomain: edumeet
  containers:
  - name: pikaworker
    image: dennismaier/pikaworker:latest
    ports:
    - containerPort: 8093
    env:
      - name: rest_url
        value: http://edumeet:8010
---
apiVersion: v1
kind: Service
metadata:
  name: svc-edumeet
  labels:
    app: edumeet
spec:
  ports:
  - port: 8443
    name: edumeet
  clusterIP: None
  selector:
    app: edumeet
---
apiVersion: v1
kind: ConfigMap
metadata:  
  name: edumeet-server-config.yaml
data:
  config.yaml: |-
    ### MEINS
    listeningPort: 8443
    listeningHost: 0.0.0.0

    fileTracker: "wss://tracker.openwebtorrent.com"

    tls:
      cert: ./certs/edumeet-demo-cert.pem
      key:  ./certs/edumeet-demo-key.pem

    # turnAPIURI: "https://host.domain.tld/turn"
    # turnAPIKey: "Your API key"

    backupTurnServers:
    - urls:
      - "stun:127.0.0.1:3478"
      username: "test"
      credential: "test123"

    redisOptions:
      host: "redis.edumeet.default.svc.cluster.local"
      port: "6379"
      password: "_REDIS_PASSWORD_"
      #url: "redis://redis.edumeet.default.svc.cluster.local:30030/1"

    prometheus:
      enabled: false
      deidentify: true
      numeric: true
      listen: host.domain.tld

    mediasoup:
      webRtcTransport:
        listenIps:
        - ip: "0.0.0.0"
      plainRtpTransport:
        listenIp:
          ip: "0.0.0.0"
        rtcpMux: true
        comedia: false

    rabbitmqOptions:
      url: "amqp://guest:guest@127.0.0.1:32690"

    bentoML:
      enabled: false
      URI: "http://127.0.0.1:3000/predict_async"

    pika:
      enabled: true

    celery:
      enabled: false
      
    emotion:
      targetFps: 10
      minFps: 5