listeningPort: 8443
listeningHost: 0.0.0.0

fileTracker: "wss://tracker.openwebtorrent.com"

tls:
  cert: ./certs/edumeet-demo-cert.pem
  key:  ./certs/edumeet-demo-key.pem

# turnAPIURI: "https://host.domain.tld/turn"
# turnAPIKey: "Your API key"

backupTurnServers:
- urls:
  - "stun:192.168.178.56:3478"
  username: "test"
  credential: "test123"


redisOptions:
  #host: "192.168.39.127"  
  host: "redis"                                                                                                                                                                
  port: "6379"            
  password: "_REDIS_PASSWORD_"
  #url: "redis://192.168.39.127:30030/1"
  url: "redis://127.0.0.1:6379/1"

rabbitmqOptions:
  url: "amqp://guest:guest@127.0.0.1:32690"                                                                                                                                                                 


prometheus:
  enabled: false
  deidentify: true
  numeric: true
  listen: host.domain.tld
   
mediasoup:
  webRtcTransport:
    listenIps:
    - ip: "0.0.0.0"
      announcedIp: "192.168.178.56"
  plainRtpTransport:
    listenIp:
      ip: "0.0.0.0"
      announcedIp: "192.168.178.56"
    rtcpMux: true
    comedia: false

bentoML:
  enabled: false
  URI: "http://192.168.39.127:3000/predict_async"

celery:
  enabled: false

pika:
  enabled: true
  
emotion:
  targetFps: 10
  minFps: 5