listeningPort: 8443
listeningHost: 0.0.0.0

fileTracker: "wss://tracker.openwebtorrent.com"

tls:
  cert: ./certs/edumeet-demo-cert.pem
  key:  ./certs/edumeet-demo-key.pem

# turnAPIURI: "https://host.domain.tld/turn"
# turnAPIKey: "Your API key"

backupTurnServers:
- urls:
  - "stun:192.168.178.39:3478"
#  - "stun:116.202.137.233:3478?transport=tcp"
  username: "test"
  credential: "test123"


redisOptions:
  host: 127.0.0.1
  port: "6379"            
  password: "_REDIS_PASSWORD_"
  url: "redis://127.0.0.1:6379/1"

rabbitmqOptions:
  url: "amqp://guest:guest@127.0.0.1:32690"
   
prometheus:
  enabled: false
  deidentify: true
  numeric: true
  listen: host.domain.tld
   
mediasoup:
  webRtcTransport:
    listenIps:
    - ip: "0.0.0.0"
      announcedIp: "192.168.178.39"
  plainRtpTransport:
    listenIp:
      ip: "0.0.0.0"
      announcedIp: "192.168.178.39"
    rtcpMux: true
    comedia: false

bentoML:
  enabled: false
  URI: "http://127.0.0.1:3000/predict_async"

celery:
  enabled: false

pika:
  enabled: true
  
emotion:
  targetFps: 10
  minFps: 5
