apiVersion: apps/v1
kind: Deployment
metadata:
  name: pika
  namespace: sensecaremeet
  labels:
    app: pika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pika
  template:
    metadata:
      labels:
        app: pika
    spec:
      containers:
      - name: pika
        image: dennismaier/pikaworker:latest
        ports:
        - containerPort: 8093
        env:
          - name: RESULT_BACKEND
            value: http://edumeet:8010

