### MEINS
listeningPort: 8443
listeningHost: 0.0.0.0

fileTracker: "wss://tracker.openwebtorrent.com"

tls:
  cert: ./certs/edumeet-demo-cert.pem
  key:  ./certs/edumeet-demo-key.pem

# für eine Liste von turns gedacht!
#turnAPIURI: "https://[FQDN]/turn"
# turnAPIKey: "Your API key"l


backupTurnServers:
- urls:
  #- "stun:192.168.178.35:3478"
  - "stun:stun.l.google.com:19302"
  #- "turn:192.168.178.35:3478"
  username: "test"
  credential: "test123"

redisOptions:
  host: "redis"
  port: "6379"
  password: "_REDIS_PASSWORD_"
  #url: "redis://127.0.0.1:30030/1"

prometheus:
  enabled: false
  deidentify: true
  numeric: true
  listen: host.domain.tld

mediasoup:
  webRtcTransport:
    listenIps:
    - ip: "0.0.0.0"
      announcedIp: "192.168.178.35"
  plainRtpTransport:
    listenIp:
      ip: "0.0.0.0"
      announcedIp: "192.168.178.35"
    rtcpMux: true
    comedia: false

rabbitmqOptions:
  url: "amqp://guest:guest@rabbitmq:5672"

bentoML:
  enabled: false
  URI: "http://127.0.0.1:3000/predict_async"

pika:
  enabled: true
  queueUrl: "amqp://guest:guest@rabbitmq:5672"

celery:
  enabled: false
  
emotion:
  targetFps: 10
  minFps: 5