apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: sensecaremeet
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
        - containerPort: 32690
        - containerPort: 5672
        - containerPort: 5671
        - containerPort: 25672
        - containerPort: 4369
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: guest
          - name: RABBITMQ_DEFAULT_PASS
            value: guest
